config/routes.rb
Rails.application.routes.draw do
  resources :tweets
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'tweets#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: %i[ show edit update destroy ]

  # GET /tweets or /tweets.json
  def index
    @tweets = Tweet.all.order('created_at DESC')
    @tweet = Tweet.new
  end

  # GET /tweets/1 or /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets or /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to @tweet, notice: "Tweet was successfully created." }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1 or /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: "Tweet was successfully updated." }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1 or /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: "Tweet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tweet_params
      params.require(:tweet).permit(:tweet)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
  <head>
    <title>Twitter</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% if flash[:notice] %>
    <div class='notification is-primary global-notification'>
      <p classs='notice'><%= notice %></p>
    </div>
  <% end %>
  <% if flash[:alert] %>
    <div class='notification is-danger global-notification'>
      <p classs='notice'><%= alert %></p>
    </div>
  <% end %>
  <nav class='navbar is-info'>
    <div class='navbar-brand'>
      <%= link_to root_path, class:'navbar-item' do%>
        <h1 class='title is-5'>Twitter</h1>
      <% end %>
      <div class='navbar-burger burger'data-target='navbarExample'>
        <span></span>
        <span></span>
        <span></span>
      </div>
    </div>

    <div id='navbarExample' class='navbar-menu'>
      <div class='navbar-end'>
        <div class='field is-grouped'>
          <p class='control'>
            <%= link_to 'New tweet', new_tweet_path, class:'button is-inverted' %>
          </p>
          <p class='control'>Sign Up</p>
        </div>
      </div>
    </div>
  </nav>

    <%= yield %>
  </body>
</html>

app/views/tweets/_feed.html.erb
<div class='column is-half'>
    <article class='media box'>
        <figure class='media-left'>
            <p class='image is-64x64'>
                <img src='https://bulma.io/images/placeholders/64x64.png'>
            </p>
        </figure>
        <div class='media-content'>
            <%= render 'tweets/form' %>
        </div>
    </article>


<% @tweets.each do |tweet| %>
    <div class='box'>
        <article class='media'>
            <div class='media-left'>
                <figure class='image is-64x64'>
                    <img src='https://bulma.io/images/placeholders/64x64.png'>
                </figure>
            </div>
            <div class='media-content'>
                <div class='content'>
                    <strong>Bhargava Gupta</strong><br />
                    <small>@bhargava<small><br />
                    <p><%= tweet.tweet %></p>
                </div>
                <nav class='level'>
                    <div class='level-left is-mobile'>
                        <%= link_to tweet,class:'level-item' do%>
                            <span class='icon'><i class='fa fa-link' aria-hidden='true'></i></span>
                        <% end %>
                        <%= link_to edit_tweet_path(tweet),class:'level-item' do%>
                            <span class='icon'><i class='fa fa-pencil' aria-hidden='true'></i></span>
                        <% end %>
                        <%= link_to tweet,method: :delete,data: { confirm: "Are you sure you want to delete this tweet"}  do%>
                            <span class='icon'><i class='fa fa-trash-o' aria-hidden='true'></i></span>
                        <% end %>
                    </div>
                </nav>
            </div>
        </article>
    </div>
<% end %>

</div>

app/views/tweets/_form.html.erb
<%= simple_form_for(@tweet) do |f|%>
  <%= f.error_notification %>
  <div class='fiels'>
    <div class='control'>
      <%= f.input :tweet, label:'Tweet About It ', input_html: {class: 'textarea'}, wrapper: false, label_html: { class: 'label'}, placeholder: 'Compose new Tweet...' %>
    </div>
  </div>
  <%= f.button :submit, class: 'button is-info'%>
<% end %>

app/views/tweets/_trends.html.erb
<div class='column is-one-quater'>
    <nav class='panel'>
        <p class='panel-heading'>Trends</p>
        <a class='panel-block'>
            Trend 1
        </a>
        <a class='panel-block'>
            Trend 2
        </a>
        <a class='panel-block'>
            Trend 3
        </a>
        <a class='panel-block'>
            Trend 4
        </a>
        <a class='panel-block'>
            Trend 5
        </a>
        <a class='panel-block'>
            Trend 6
        </a>
        
    </nav>
</div>

app/views/tweets/_who-to-follow.html.erb
<div class='column'>
    <nav class='panel'>
        <p class='panel-heading'>Who to follow</p>

        <div class='panel-block'>
            <article class='media'>
                <div class='media-left'>
                    <figure class='image is-32x32'>
                        <img src='https://bulma.io/images/placeholders/64x64.png'>
                    </figure>
                </div>
                <div class='media-content'>
                    <div class='content'>
                        <p>
                        <strong>Bhargava Gupta</strong>
                        <small>@bhargava<small>
                        </p>
                    </div>
                </div>
            </article>
        </div>
        <div class='panel-block'>
            <article class='media'>
                <div class='media-left'>
                    <figure class='image is-32x32'>
                        <img src='https://bulma.io/images/placeholders/64x64.png'>
                    </figure>
                </div>
                <div class='media-content'>
                    <div class='content'>
                        <p>
                        <strong>Bhargava Gupta</strong>
                        <small>@bhargava<small>
                        </p>
                    </div>
                </div>
            </article>
        </div>
        <div class='panel-block'>
            <article class='media'>
                <div class='media-left'>
                    <figure class='image is-32x32'>
                        <img src='https://bulma.io/images/placeholders/64x64.png'>
                    </figure>
                </div>
                <div class='media-content'>
                    <div class='content'>
                        <p>
                        <strong>Bhargava Gupta</strong>
                        <small>@bhargava<small>
                        </p>
                    </div>
                </div>
            </article>
        </div>
    </nav>
</div>

app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<section class='section'>
  <div class='container'>
    <div class='columns'>
      <%= render 'trends' %>
      <%= render 'feed' %>
      <%= render 'who-to-follow' %>
    </div>
  </div>
</section>
    

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tweet:</strong>
  <%= @tweet.tweet %>
</p>

<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>